//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Editorial { get; set; }
        public string Image { get; set; }
        public int Fk_Author_Id { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
